#!/bin/sh
set -e

# GLOBAL VARIABLES

# Name of the house
CLUSTER_ID="petitbijou"

# Maintainer of the cluster configuration files
CLUSTER_MAINTAINER="Eric <petitbijou.caussade@gmail.com>"

# Full human-readable name of the house
CLUSTER_HUMAN_NAME="💎Petit Bijou de Caussade💎"

# APT repository URL to get the updates and packages specifically for this cluster (Ensemble packages and Component packages).
CLUSTER_APT_REPO_URL="https://github.com/etnz/reserve/releases/download/repo"

# URL to the public GPG key used to sign the APT repository.
CLUSTER_PUBLIC_KEY_URL="https://github.com/etnz/reserve/releases/download/repo/public.gpg"

# Path to the local copy of the public GPG key used to verify the APT repository.
CLUSTER_PUBLIC_KEY="/etc/apt/keyrings/$CLUSTER_ID.gpg"


# local Variables

# Self version
VERSION="1.0.0"




# postinst is called with different arguments depending on the package lifecycle:
#     configure, abort-upgrade	triggered abort-remove
# As long as the script is idempotent AND quick it is safe (and simpler) to execute it on all those phases.

echo "🎙️ $CLUSTER_HUMAN_NAME"
# Private key for the node
mkdir -p "/etc/$CLUSTER_ID"
if [ ! -f "/etc/$CLUSTER_ID/node_id" ]; then
    ssh-keygen -t ed25519 -f "/etc/$CLUSTER_ID/node_id" -N "" -q
fi

# Repository Configuration (Idempotent: only creates if missing)
mkdir -p /etc/apt/keyrings
if [ ! -f "$CLUSTER_PUBLIC_KEY" ]; then
    curl -sSL "$CLUSTER_PUBLIC_KEY_URL" -o "$CLUSTER_PUBLIC_KEY"
fi 

cat <<EOF > "/etc/apt/sources.list.d/$CLUSTER_ID.sources"
Types: deb
URIs: $CLUSTER_APT_REPO_URL/
Suites: ./
Signed-By: $CLUSTER_PUBLIC_KEY
EOF

echo "🛎️ The Letter of Introduction v$VERSION has been accepted."