#!/bin/sh
set -e

#GLOBAL VARIABLES


# Name of the house
CLUSTER_ID="petitbijou"

# Maintainer of the cluster configuration files
CLUSTER_MAINTAINER="Eric <petitbijou.caussade@gmail.com>"

# Full human-readable name of the house
CLUSTER_HUMAN_NAME="💎Petit Bijou de Caussade💎"

# APT repository URL to get the updates and packages specifically for this cluster (Ensemble packages and Component packages).
CLUSTER_APT_REPO_URL="https://github.com/etnz/reserve/releases/download/repo"

# URL to the public GPG key used to sign the APT repository.
CLUSTER_PUBLIC_KEY_URL="https://github.com/etnz/reserve/releases/download/repo/public.gpg"

# Path to the local copy of the public GPG key used to verify the APT repository.
CLUSTER_PUBLIC_KEY="/etc/apt/keyrings/$CLUSTER_ID.gpg"

# Local Variables

# Self version
VERSION="1.0.0"

# prerm is called with different arguments depending on the package lifecycle:
#      remove, upgrade <new-version>, deconfigure, failed-upgrade <old-version>
# As long as the script is idempotent AND quick it is safe (and simpler) to execute it on all those phases.

echo "🎙️ $CLUSTER_HUMAN_NAME"

# Remove the APT source list
if [ -f "/etc/apt/sources.list.d/$CLUSTER_ID.sources" ]; then
    rm -f "/etc/apt/sources.list.d/$CLUSTER_ID.sources"
fi

# Remove the public keyring
if [ -f "$CLUSTER_PUBLIC_KEY" ]; then
    rm -f "$CLUSTER_PUBLIC_KEY"
fi

echo "🛎️ The Letter of Introduction v$VERSION has been revoked."